routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function () {
    Route::resource('services', 'ServiceController');
    Route::resource('website_sections', 'Website_sectionController');
    Route::resource('references', 'ReferencesController');
    Route::resource('groups', 'GroupController');
});
//Route::post('/konkurss/{konkurss}/detail', 'PersonController@store')->name('storeprojects');

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    //
}

app/Http/Controllers/API/ServicesController.php
<?php

namespace App\Http\Controllers\API;

use App\Service;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ServicesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Service::all();
        $out = [];
        foreach($services  as $service) {
            unset($service['created_at']);
            unset($service['updated_at']);
            $out[] = $service;
        }
        return $out;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Service;
use Illuminate\Http\Request;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Service::all();
        return view('service.index',  compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('service.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $service = new Service();
       $service->title = $request['title'];
       $service->content = $request['content'];
       $service->image = $request['image'];
       $service->save();
       return redirect('../public/services');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function show(Service $service)
    {
        return view('service.show',  compact('service'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit(Service $service)
    {
        return view('service.edit',  compact('service'));

    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Service $service)
    {
        $service->title = $request['title'];
        $service->content = $request['content'];
        $service->image = $request['image'];
        $service->save();
        return redirect('../public/services');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy(Service $service)
    {
        $service->delete();

        return redirect('../public/services');
    }
}

resources/views/service/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Add Service</h1>
        <form method="POST" action="{{ route('services.store') }}">
            {{ csrf_field() }}
            <div class="form-group">
                <h3>Title</h3>
                <input type="text" name="title" value="" placeholder="title">
            </div>
            <div class="form-group">
                <h3>Content</h3>
            <input type="text" name="content" value="" placeholder="content">
            </div>
                <div class="form-group">
                    <h3>Image</h3>
            <input type="text" name="image" value="" placeholder="image">
                </div>
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
@endsection

resources/views/service/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Edit Service [{{ $service->title }}]</h1>
        <form method="POST" action="{{ route('services.update', $service->id) }}">
            {{ csrf_field() }}
            @method('PUT')
            <div class="form-group">
                <input type="text" name="title" value="{{ $service->title }}">
            </div>
                <div class="form-group">
                <input type="text" name="image" value="{{ $service->image }}">
                </div>
                    <div class="form-group">
                <input type="text" name="content" value="{{ $service->content }}">
            </div>
            <a href="/webpro/public/services" class="btn btn-success">Back</a>
            <input type="submit" value="Submit" class="btn btn-primary">

        </form>
        <form action="{{ route('services.destroy', $service->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger mt-2" type="submit">Delete</button>
        </form>
    </div>


@endsection

resources/views/service/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <table>
        <th>Service Name</th>
        <th><a href="{{ URL('api/services')}}" class="btn btn-danger">Api</a></th>
    </table>
    @foreach($services as $service)
        <table>
            <tr>
                <td>{{  $service->title }}</td>
                <td><a href="{{ URL('services/'.$service->id )}}" class="btn btn-success">Info</a></td>
                <td><a href="{{ URL('services/'.$service->id.'/edit/' )}}" class="btn btn-warning">Edit</a></td>
                <td><form action="{{ route('services.destroy', $service->id)}}" method="post">
                        @csrf
                        @method('DELETE')

                        <button class="btn btn-danger" type="submit">Delete</button>

                    </form></td>
            </tr>
        </table>

    @endforeach
</div>


@endsection

resources/views/service/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <p><span>Id: </span>{{ $service->id }}</p>
        <p><span>Image: </span><img src="{{ asset($service->image) }}" style="width:250px;height:250px;"></p>
        <p><span>Name: </span>{{ $service->title }}</p>
        <p><span>Content: </span>{{ $service->content }}</p>
        <a href="{{ URL('services/')}}" class="btn btn-danger">Back</a>
    </div>
@endsection