routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function () {
    Route::resource('services', 'ServiceController');
    Route::resource('website_sections', 'Website_sectionController');
    Route::resource('references', 'ReferencesController');
    Route::resource('groups', 'GroupController');
});
//Route::post('/konkurss/{konkurss}/detail', 'PersonController@store')->name('storeprojects');

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    public $table = "groups";
    protected $fillable = ['name'];
}

app/Http/Controllers/API/GroupController.php
<?php

namespace App\Http\Controllers\API;

use App\Group;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = group::all();
        $out = [];
        foreach($groups as $group) {
            unset($group['created_at']);
            unset($group['updated_at']);
            $out[] = $group;
        }
        return $out;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Group;
use Illuminate\Http\Request;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = group::all();
        return view('group.index',  compact('groups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('group.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $group = new group();
        $group->group_title = $request['group_title'];
        $group->save();
        return redirect('../public/groups');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(group $group)
    {
        return view('group.show',  compact('group'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(group $group)
    {
        return view('group.edit',  compact('group'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, group $group)
    {
        $group->group_title = $request['group_title'];
        $group->save();
        return redirect('../public/groups');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(group $group)
    {
        $group->delete();

        return redirect('../public/groups');
    }
}

resources/views/group/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Add Group</h1>
        <form method="POST" action="{{ route('groups.store') }}">
            {{ csrf_field() }}
            <div class="form-group">
                <h3>Group Title</h3>
                <input type="text" name="group_title" value="" placeholder="title">
            </div>
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
@endsection

resources/views/group/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Edit [{{ $group->group_title }}]</h1>
        <form method="POST" action="{{ route('groups.update', $group->id) }}">
            {{ csrf_field() }}
            @method('PUT')
            <div class="form-group">
                <h3>Group_title</h3>
                <input type="text" name="group_title" value="{{ $group->group_title }}">
            <a href="/webpro/public/groups" class="btn btn-success">Back</a>
            <input type="submit" value="Submit" class="btn btn-primary">

        </form>
        <form action="{{ route('groups.destroy', $group->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger mt-2" type="submit">Delete</button>
        </form>
    </div>


@endsection

resources/views/group/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <table>
            <th>Group Name</th>
            <th><a href="{{ URL('api/group')}}" class="btn btn-danger">Api</a></th>
        </table>
        @foreach($groups as $group)
            <table>
                <tr>
                    <td>{{  $group->group_title }}</td>
                    <td><a href="{{ URL('groups/'.$group->id )}}" class="btn btn-success">Info</a></td>
                    <td><a href="{{ URL('groups/'.$group->id.'/edit/' )}}" class="btn btn-warning">Edit</a></td>
                    <td><form action="{{ route('groups.destroy', $group->id)}}" method="post">
                            @csrf
                            @method('DELETE')

                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form></td>
                </tr>
            </table>

        @endforeach
    </div>


@endsection

resources/views/group/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <p><span>Id: </span>{{ $group->id }}</p>
        <p><span>Group_Title: </span>{{ $group->group_title }}</p>
        <a href="{{ URL('groups/')}}" class="btn btn-danger">Back</a>
    </div>
@endsection