routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function () {
    Route::resource('services', 'ServiceController');
    Route::resource('website_sections', 'Website_sectionController');
    Route::resource('references', 'ReferencesController');
    Route::resource('groups', 'GroupController');
});
//Route::post('/konkurss/{konkurss}/detail', 'PersonController@store')->name('storeprojects');

app/website_section.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class website_section extends Model
{
    //
}

app/Http/Controllers/API/Website_sectionController.php
<?php

namespace App\Http\Controllers\API;

use App\website_section;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class Website_sectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $website_sections = Website_section::all();
        $out = [];
        foreach($website_sections as $website_section) {
            unset($website_section['created_at']);
            unset($website_section['updated_at']);
            $out[] = $website_section;
        }
        return $out;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Website_sectionController.php
<?php

namespace App\Http\Controllers;

use App\website_section;
use Illuminate\Http\Request;

class Website_sectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $website_sections = Website_section::all();
            return view('website_section.index',compact('website_sections'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('website_section.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $website_section = new Website_section();
        $website_section->menu_title = $request->input['menu_title'];
        $website_section->title = $request->input['title'];
        $website_section->content = $request->input['content'];
        $website_section->save();
        return redirect('../public/website_sections');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Website_section $website_section)
    {
        return view('website_section.show',  compact('website_section'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Website_section $website_section)
    {
        return view('website_section.edit',  compact('website_section'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Website_section $website_section)
    {
        $website_section->menu_title = $request['menu_title'];
        $website_section->title = $request['title'];
        $website_section->content = $request['content'];
        $website_section->save();
        return redirect('../public/website_sections');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Website_section $website_section)
    {
        $website_section->delete();
        return redirect('../public/website_sections');
    }
}

resources/views/website_section/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Add Section</h1>
        <form method="POST" action="{{ route('website_sections.store') }}">
            {{ csrf_field() }}
            <div class="form-group">
                <h3>Menu_title</h3>
                <input type="text" name="menu_title" value="" placeholder="menu_title">
            </div>
            <div class="form-group">
                <h3>Title</h3>
                <input type="text" name="title" value="" placeholder="title">
            </div>
            <div class="form-group">
                <h3>Content</h3>
                <input type="text" name="content" value="" placeholder="content">
                @section('js')
                    <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
                    <script>
                        CKEDITOR.replace( 'content' );
                    </script>
                @append
            </div>
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
@endsection

resources/views/website_section/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Edit Service [{{ $website_section->title }}]</h1>
        <form method="POST" action="{{ route('services.update', $website_section->id) }}">
            {{ csrf_field() }}
            @method('PUT')
            <div class="form-group">
                <input type="text" name="menu_title" value="{{ $website_section->menu_title }}">
            </div>
            <div class="form-group">
                <input type="text" name="title" value="{{ $website_section->title }}">
            </div>
            <div class="form-group">
                <input type="text" name="content" value="{{ $website_section->content }}">
            </div>
            <a href="/webpro/public/website_sections" class="btn btn-success">Back</a>
            <input type="submit" value="Submit" class="btn btn-primary">

        </form>
        <form action="{{ route('website_sections.destroy', $website_section->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger mt-2" type="submit">Delete</button>
        </form>
    </div>


@endsection

resources/views/website_section/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <table>
            <th>Section Name</th>
            <th><a href="{{ URL('api/website_sections')}}" class="btn btn-danger">Api</a></th>
        </table>
        @foreach($website_sections as $website_section)
            <table>
                <tr>
                    <td>{{  $website_section->title }}</td>
                    <td><a href="{{ URL('website_sections/'.$website_section->id )}}" class="btn btn-success">Info</a></td>
                    <td><a href="{{ URL('website_sections/'.$website_section->id.'/edit/' )}}" class="btn btn-warning">Edit</a></td>
                    <td><form action="{{ route('website_sections.destroy', $website_section->id)}}" method="post">
                            @csrf
                            @method('DELETE')

                            <button class="btn btn-danger" type="submit">Delete</button>

                        </form></td>
                </tr>
            </table>

        @endforeach
    </div>


@endsection

resources/views/website_section/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <p><span>Id: </span>{{ $website_section->id }}</p>
        <p><span>Menu_Title: </span>{{ $website_section->menu_title }}</p>
        <p><span>Title: </span>{{ $website_section->title }}</p>
        <p><span>Content: </span>{{ $website_section->content }}</p>
        <a href="{{ URL('website_sections/')}}" class="btn btn-danger">Back</a>
    </div>
@endsection