routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function () {
    Route::resource('services', 'ServiceController');
    Route::resource('website_sections', 'Website_sectionController');
    Route::resource('references', 'ReferencesController');
    Route::resource('groups', 'GroupController');
});
//Route::post('/konkurss/{konkurss}/detail', 'PersonController@store')->name('storeprojects');

app/references.php
<?php

namespace App;

use Cviebrock\EloquentTaggable\Taggable;
use Illuminate\Database\Eloquent\Model;

class references extends Model
{
    use Taggable;
    public $table = "references";

    protected $fillable = ['group_id', 'group', 'url', 'title'];

    function groups(){
        return $this->belongsTo('App\Group');
    }
}

app/Http/Controllers/API/ReferencesController.php
<?php

namespace App\Http\Controllers\API;

use App\references;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ReferencesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $references = references::all();
        $out = [];
        foreach($references as $reference) {
            unset($reference['created_at']);
            unset($reference['updated_at']);
            $out[] = $reference;
        }
        return $out;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/ReferencesController.php
<?php

namespace App\Http\Controllers;

use App\references;
use App\Group;
use Illuminate\Http\Request;

class ReferencesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $references = references::all();
        return view('reference.index',  compact('references'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Group $group)
    {
        $groups = Group::all();
        return view('reference.create', compact('groups'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Group $groups)
    {
        $reference = new references();
        $reference->group = $request['group'];
        $reference->url = $request['url'];
        $reference->title = $request['title'];
        $reference->save();
        return redirect('../public/references');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function show(references $reference)
    {
        return view('reference.show',  compact('reference'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit(references $reference, Group $groups)
    {
        $groups = Group::all();
        return view('reference.edit',  compact('reference', 'groups'));

    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,references $reference , Group $groups)
    {
        $reference->group = $request['group'];
        $reference->url = $request['url'];
        $reference->title = $request['title'];
        $reference->save();
        return redirect('../public/references');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy(references $reference)
    {
        $reference->delete();

        return redirect('../public/references');
    }
}

resources/views/reference/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Add References</h1>
        <form method="POST" action="{{ route('references.store') }}">
            {{ csrf_field() }}
            <div class="form-group">
                <h3>Group</h3>
                <select type="text" name="group">
                @foreach($groups as $group)
                    <option type="text" name="group"  value="{{ $group->group_title }}">{{ $group->group_title }}</option>
                @endforeach
                </select>
            </div>
            <div class="form-group">
                <h3>Url</h3>
                <input type="text" name="url" value="" placeholder="url">
            </div>
            <div class="form-group">
                <h3>Title</h3>
                <input type="text" name="title" value="" placeholder="title">
            </div>
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
@endsection

resources/views/reference/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Edit [{{ $reference->title }}]</h1>
        <form method="POST" action="{{ route('references.update', $reference->id) }}">
            {{ csrf_field() }}
            @method('PUT')
            <div class="form-group">
                <h3>Group</h3>
                <select type="text" name="group">
                    @foreach($groups as $group)
                        <option type="text" name="group"  value="{{ $group->id }}">{{ $group->group_title }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <h3>Url</h3>
                <input type="text" name="url" value="{{ $reference->url }}">
            </div>
            <div class="form-group">
                <h3>Title</h3>
                <input type="text" name="title" value="{{ $reference->title }}">
            </div>
            <a href="/webpro/public/references" class="btn btn-success">Back</a>
            <input type="submit" value="Submit" class="btn btn-primary">

        </form>
        <form action="{{ route('references.destroy', $reference->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger mt-2" type="submit">Delete</button>
        </form>
    </div>


@endsection

resources/views/reference/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <table>
            <th>Reference Name /</th>
            <th>Group</th>
            <th><a href="{{ URL('api/references')}}" class="btn btn-danger">Api</a></th>
        </table>
        @foreach($references as $reference)
            <table>
                <tr>
                    <td>{{  $reference->title .' /'}}</td>
                    <td>{{ $reference->group }}</td>
                    <td><a href="{{ URL('references/'.$reference->id )}}" class="btn btn-success">Info</a></td>
                    <td><a href="{{ URL('references/'.$reference->id.'/edit/' )}}" class="btn btn-warning">Edit</a></td>
                    <td><form action="{{ route('references.destroy', $reference->id)}}" method="post">
                            @csrf
                            @method('DELETE')

                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form></td>
                </tr>
            </table>

        @endforeach
    </div>


@endsection

resources/views/reference/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <p><span>Id: </span>{{ $reference->id }}</p>
        <p><span>Group Number: </span>{{ $reference->group }}</p>
        <p><span>Url: </span>{{ $reference->url }}</p>
        <p><span>Title: </span>{{ $reference->title }}</p>
        <a href="{{ URL('references/')}}" class="btn btn-danger">Back</a>
    </div>
@endsection